# -*- coding: utf-8 -*-
facebookText = u"""
Facebook, American company offering online social networking services. Facebook was founded in 2004 by Mark Zuckerberg, Eduardo Saverin, Dustin Moskovitz, and Chris Hughes, all of whom were students at Harvard University. Facebook became the largest social network in the world, with more than one billion users as of 2012, and about half that number were using Facebook every day. The company's headquarters are in Menlo Park, California.
Access to Facebook is free of charge, and the company earns most of its money from advertisements on the Web site. New users can create profiles, upload photos, join a preexisting group, and start new groups. The site has many components, including Timeline, a space on each user's profile page where users can post their content and friends can post messages; Status, which enables users to alert friends to their current location or situation; and News Feed, which informs users of changes to their friends' profiles and status. Users can chat with each other and send each other private messages. Users can signal their approval of content on Facebook with the Like button, a feature that also appears on many other Web sites.
The attractiveness of Facebook stems in part from cofounder Zuckerberg's insistence from the very beginning that members be transparent about who they are; users are forbidden from adopting false identities. The company's management argued that transparency is necessary for forming personal relationships, sharing ideas and information, and building up society as a whole. It also noted that the bottom-up, peer-to-peer connectivity among Facebook users makes it easier for businesses to connect their products with consumers.
The company has a complicated early history. It began at Harvard University in 2003 as Facemash, an online service for students to judge the attractiveness of their fellow students. Because the primary developer, Zuckerberg, violated university policy in acquiring resources for the service, it was shut down after two days. Despite its mayflylike existence, 450 people (who voted 22,000 times) flocked to Facemash. That success prompted Zuckerberg to register the URL http://www.thefacebook.com in January 2004. He then created a new social network at that address with fellow students Saverin, Moskovitz, and Hughes.
The social network TheFacebook.com launched in February 2004. Harvard students who signed up for the service could post photographs of themselves and personal information about their lives, such as their class schedules and clubs they belonged to. Its popularity increased, and soon students from other prestigious schools, such as Yale and Stanford universities, were allowed to join. By June 2004 more than 250,000 students from 34 schools had signed up, and that same year major corporations such as the credit-card company MasterCard started paying for exposure on the site.
In September 2004 TheFacebook added the Wall to a member's online profile. This widely used feature let a user's friends post information on their Wall and became a key element in the social aspect of the network. By the end of 2004, TheFacebook had reached one million active users. However, the company still trailed the then-leading online social network, Myspace, which boasted five million members.
The year 2005 proved to be pivotal for the company. It became simply Facebook and introduced the idea of "tagging" people in photos that were posted to the site. With tags, people identified themselves and others in images that could be seen by other Facebook friends. Facebook also allowed users to upload an unlimited number of photos. In 2005 high-school students and students at universities outside the United States were allowed to join the service. By year's end it had six million monthly active users.
In 2006 Facebook opened its membership beyond students to anyone over the age of 13. As Zuckerberg had predicted, advertisers were able to create new and effective customer relationships. For example, that year, household product manufacturer Procter & Gamble attracted 14,000 people to a promotional effort by "expressing affinity" with a teeth-whitening product. This kind of direct consumer engagement on such a large scale had not been possible before Facebook, and more companies began using the social network for marketing and advertising.
Privacy remains an ongoing problem for Facebook. It first became a serious issue for the company in 2006, when it introduced News Feed, which consisted of every change that a user's friends had made to their pages. After an outcry from users, Facebook swiftly implemented privacy controls in which users could control what content appeared in News Feed. In 2007 Facebook launched a short-lived service called Beacon that let members' friends see what products they had purchased from participating companies. It failed because members felt that it encroached on their privacy. Indeed, a survey of consumers in 2010 put Facebook in the bottom 5 percent of companies in customer satisfaction largely because of privacy concerns, and the company continues to be criticized for the complexity of its user privacy controls and for the frequent changes it makes to them.
In 2008 Facebook surpassed Myspace as the most-visited social media Web site. With the introduction of Live Feed, the company also took a competitive swing at the growing popularity of Twitter, a social network that runs a live feed of news service-like posts from members whom a user follows. Similar to Twitter's ongoing stream of user posts, Live Feed pushed posts from friends automatically to a member's homepage. (Live Feed has since been incorporated into News Feed.)
Facebook has become a powerful tool for political movements, beginning with the U.S. presidential election of 2008, when more than 1,000 Facebook groups were formed in support of either Democratic candidate Barack Obama or Republican candidate John McCain. In Colombia the service was used to rally hundreds of thousands in protests against the antigovernment FARC guerrilla rebellion. In Egypt, activists protesting the government of Pres. Ḥosnī Mubārak during the uprising of 2011 often organized themselves by forming groups on Facebook.
Facebook encourages third-party software developers to use the service. In 2006 it released its application programming interface (API) so that programmers could write software that Facebook members could use directly through the service. By 2009 developers generated about $500 million in revenue for themselves through Facebook. The company also earns revenues from developers through payments for virtual or digital products sold through third-party applications. By 2011 payments from one such company, Zynga Inc., an online game developer, accounted for 12 percent of the company's revenues.
In February 2012 Facebook filed to become a public company. Its initial public offering (IPO) in May raised $16 billion, giving it a market value of $102.4 billion. By contrast, the largest IPO of an Internet company to date was that of the search-engine company Google Inc., which had raised $1.9 billion when it went public in 2004. By the end of the first day of the stock's trading, Zuckerberg's holdings were estimated at more than $19 billion."""

myspaceText = u"""
Myspace, social networking Web site owned by online advertising company Specific Media and singer Justin Timberlake and headquartered in Beverly Hills, Calif.
Myspace is a free, advertising-supported service that allows users to create Web "profile" pages that feature photographs, express their interests, and, most importantly, link to other people's profiles. The site can be used to keep in touch with friends, "meet" and become friends with new people, or find potential romantic partners. Members must be at least 13 years old, and the profiles of members younger than 16 cannot be viewed by members older than 18, in order to reduce access by potential sexual predators.
Tom Anderson and Chris DeWolfe, employees of the Internet marketing company eUniverse (later Intermix Media), created Myspace in 2003. It quickly distinguished itself from established social networking sites by allowing—and in fact encouraging—musical artists to use the site to promote themselves, earning Myspace a hip cachet and making it a favoured destination site for youth. It also developed a reputation for racier profiles and a raunchier attitude than other sites. In 2005 Rupert Murdoch's News Corporation purchased Myspace and Intermix for $580 million, bringing Anderson and DeWolfe along.
While the site's user base continued to expand rapidly, some parents, community groups, and state and local governments worried that young teenagers—among whom Myspace had become ubiquitous—were being exposed to potential sexual predators. In 2006 the company began detecting and deleting profiles of registered sex offenders and partnered with Sentinel Tech Holdings Corp. to develop the first national database of convicted sex offenders. Alongside such security-related innovations, Myspace pursued a steady rollout of new features, including a Myspace record label and partnerships with other services, such as the video-sharing Web site YouTube.
Membership sharply declined in the face of competition from the social networking site Facebook, and in 2009 Myspace attempted to rebrand itself as primarily a music site. In 2011 News Corporation sold Myspace to Specific Media and Timberlake for about $35 million."""

twitterText = u"""
Twitter, online microblogging service for distributing short messages among groups of recipients via personal computer or mobile telephone. Twitter incorporates aspects of social networking Web sites, such as Myspace and Facebook, with instant messaging technologies to create networks of users who can communicate throughout the day with brief messages, or "tweets." A user types a tweet via mobile phone keypad or computer and sends it to Twitter's server, which relays it to a list of other users (known as followers) who have signed up to receive the sender's tweets by either text message to their mobile phones or by instant message to their personal computers. In addition, users can elect to track specific topics, creating a dialogue of sorts and pushing the number of followers in a given Twitter feed into the millions. Tweets may be on any subject, ranging from jokes to news to dinner plans, but they cannot exceed 140 characters.
Twitter was built using Ruby on Rails, a specialized Web-application framework for the Ruby computer programming language. Its interface allows open adaptation and integration with other online services. The service was designed in 2006 by Evan Williams and Biz Stone, each of whom worked at Google before leaving to launch the podcasting venture Odeo. Williams, who had previously created the popular Web authoring tool Blogger, began experimenting with one of Odeo's side projects—a short message service (SMS) then called Twttr. Seeing a future for the product, Williams bought out Odeo and started Obvious Corp. to further develop it. Engineer Jack Dorsey joined the management team, and the completed version of Twitter debuted at the South by Southwest music conference in Austin, Texas, in March 2007. The following month Twitter, Inc., was created as a corporate entity, thanks to an infusion of venture capital.
From its inception Twitter was primarily a free SMS with a social networking element. As such, it lacked the clear revenue stream that one could find on sites that derived income from banner advertising or membership fees. With the number of unique visitors increasing some 1,300 percent in 2009, it was obvious that Twitter was more than a niche curiosity. However, in a year that saw the social networking juggernaut Facebook turn a profit for only the first time, it was not clear whether Twitter could achieve financial independence from its venture capital investors. In April 2010 Twitter unveiled "Promoted Tweets"—advertisements that would appear in search results—as its intended primary revenue source.
Twitter's social networking roots were obvious in April 2009, when actor Ashton Kutcher emerged as the victor in a race with CNN to become the first Twitterer to collect more than a million followers. While celebrity "e-watching" remained a significant draw to the service, businesses soon began sending tweets about promotions and events, and political campaigns discovered the value of Twitter as a communication tool. In the 2008 U.S. presidential election, Barack Obama dominated his opponent, John McCain, in the social media sphere, amassing almost four times as many Myspace friends and more than 20 times as many Twitter followers. This development virtually ensured that future candidates would include a social networking presence as part of their media strategies.
Perhaps the most noteworthy step in the evolution of Twitter, though, was its increased use as a tool for amateur journalists. Twitter transformed from something that was regarded as an idle hobby for an increasingly wired world into an up-to-the-second news source that transcended political borders. On January 15, 2009, a tweet by commuter ferry passenger Janis Krums broke the story of the successful water landing of US Airways Flight 1549 on the Hudson River in New York City. A hastily snapped camera phone image of passengers disembarking the half-submerged aircraft was uploaded to Twitpic.com, a photo-hosting service for Twitter users; the site promptly crashed as thousands of Twitterers attempted to view it at once.
Twitter truly established itself as an emerging outlet for the dissemination of information during the events surrounding the Iranian presidential election in June 2009. As state media sources reported that Pres. Mahmoud Ahmadinejad had secured an easy victory, supporters of opposition candidate Mir Hossein Mousavi took to the streets in a series of demonstrations that eventually provoked a crackdown by the government, in which some demonstrators were injured or killed. The topic #IranElection became one of the most followed on Twitter, as Mousavi supporters coordinated protests and posted live updates of events throughout the Iranian capital. On June 15, three days after the election, Twitter delayed a 90-minute maintenance period at the request of the U.S. State Department, rescheduling it for 1:30 am Tehrān time so as not to interfere with the flow of information within and from Iran. The following day, foreign journalists were banned from covering opposition rallies, and Twitter, along with other social networking sites, filled the void left by the traditional media. Government security officers tried to stanch the flow of information by blocking individual Twitterers, while opposition supporters urged #IranElection followers to change their profile settings to the Tehrān time zone in an attempt to overwhelm government filters. Although the protests did not result in a change in the election results or a new election, the tweets of de facto journalists showed the potential of nontraditional media to circumvent government censorship.
Having demonstrated its versatility as a high-tech newswire, Twitter drew the attention of those who would prefer to see certain information suppressed. In August 2009 a Georgian economics professor whose tweets recounted the days leading up to the 2008 military conflict between Russia and Georgia was the target of a massive denial-of-service attack that knocked out the entire site for hours. Millions of users attempted to log into Twitter only to be greeted by the service's iconic "fail whale"—the image of a cartoon whale being hoisted into the air by a flock of birds, signaling a site outage.
Following the earthquake that struck Haiti in January 2010, Twitter reaffirmed its role as a powerful tool for the dissemination of information. Additionally, it became an effective fund-raising platform, when the Red Cross launched a mobile giving campaign that surpassed all expectations. High-profile users tweeted about the drive to help victims of the earthquake, and many of their followers tweeted and re-tweeted the message, helping the Red Cross raise more than $8 million through text messaging within 48 hours of the quake.
In September 2013 Twitter filed to become a public company. (It announced the news to the public in a tweet.) Its initial public offering (IPO) in November raised $1.8 billion, giving it a market value of $31 billion."""
